OnlinePictureStorage/ViewModels/Share.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OnlinePictureStorage.ViewModels
{
    public class Share
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
    }
}

OnlinePictureStorage/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace OnlinePictureStorage.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

OnlinePictureStorage/Pages/File.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Azure.Storage.Blobs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using OnlinePictureStorage.Constants;
using OnlinePictureStorage.ViewModels;

namespace OnlinePictureStorage.Pages
{
    [Authorize]

    public class FileModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string pid { get; set; }

        [BindProperty]
        public Edit EModel { get; set; }
        
        [BindProperty]
        public Guest GModel { get; set; }

        public string link { get; set; }
        public string fname { get; set; }

        public char oorg { get; set;  }

        public string mphotographer { get; set; }
        public string mcity { get; set; }
        public string mcapturedate { get; set; }
        public List<string> mguests { get; set; }

        private readonly UserManager<IdentityUser> userManager;

        public FileModel(UserManager<IdentityUser> userManager)
        {
            this.userManager = userManager;
        }

        public IActionResult OnGet()
        {
            string userid = userManager.GetUserId(HttpContext.User);

            if (Ownership(pid, userid))
            {
                oorg = 'o';
            }
            else if(IsGuest(pid, userid))
            {
                oorg = 'g';
            }
            else
            {
                return RedirectToPage("/Home");
            }

            fname =  GetLink(pid);
            link = Connections.blobLink + fname;
            GetOriginal(pid);
            GetGuests(pid);

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            UpdateDatabase(pid, EModel.Photographer, EModel.City, EModel.Date);

            return RedirectToPage("/Home");
        }

        public async Task<IActionResult> OnPostDeleteAsync()
        {
            BlobServiceClient blobServiceClient = new BlobServiceClient(Connections.blobConnectionString);
            BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient(Connections.blobContainer);
            BlobClient blobClient = containerClient.GetBlobClient(GetLink(pid));
            await blobClient.DeleteIfExistsAsync();

            DeleteData(pid);

            return RedirectToPage("/Home");
        }

        public  IActionResult OnPostDeclineShare()
        {
            string userid = userManager.GetUserId(HttpContext.User);

            DeleteShare(pid, userid);

            return RedirectToPage("/SharedWithMe");
        }

        public IActionResult OnPostUnshare()
        {
            string guestid = GetGuestId(GModel.Email);

            DeleteShare(pid, guestid);

            return RedirectToPage("/Home");
        }

        public bool Ownership(string pid, string userid)
        {
            string gotuserid = "";

            using SqlConnection connection = new SqlConnection(Connections.sqlConnectionString);
            using SqlCommand command = connection.CreateCommand();
            command.CommandText = "SELECT userid "
                                + "FROM UserPictures "
                                + "WHERE pictureid = @pid";

            command.Parameters.AddWithValue("@pid", pid);

            connection.Open();

            SqlDataReader reader = command.ExecuteReader();
            try
            {
                while (reader.Read())
                {
                    gotuserid = String.Format("{0}", reader[0]);
                }
            }
            finally
            {
                reader.Close();
            }

            return (userid == gotuserid);
        }

        public bool IsGuest(string pictureid, string guestid)
        {
            string gotguestid = "";

            using SqlConnection connection = new SqlConnection(Connections.sqlConnectionString);
            using SqlCommand command = connection.CreateCommand();
            command.CommandText = "SELECT guestid "
                                + "FROM SharedPictures "
                                + "WHERE pictureid = @pid";

            command.Parameters.AddWithValue("@pid", pid);

            connection.Open();

            SqlDataReader reader = command.ExecuteReader();
            try
            {
                while (reader.Read())
                {
                    gotguestid = String.Format("{0}", reader[0]);
                }
            }
            finally
            {
                reader.Close();
            }

            return (guestid == gotguestid);
        }

        public string GetLink(string pictureid)
        {
            string gotlink ="";

            using SqlConnection connection = new SqlConnection(Connections.sqlConnectionString);
            using SqlCommand command = connection.CreateCommand();
            command.CommandText = "SELECT path "
                                + "FROM Pictures "
                                + "WHERE pictureid = @pid";

            command.Parameters.AddWithValue("@pid", pictureid);

            connection.Open();

            SqlDataReader reader = command.ExecuteReader();
            try
            {
                while (reader.Read())
                {
                    gotlink = String.Format("{0}", reader[0]);
                }
            }
            finally
            {
                reader.Close();
            }

            return gotlink;
        }

        public void UpdateDatabase(string pid, string photographer, string city, DateTime capturedate)
        {
            using (SqlConnection connection = new SqlConnection(Connections.sqlConnectionString))
            using (SqlCommand command = connection.CreateCommand())
            {
                command.CommandText = "UPDATE Pictures "
                                    + "SET photographer = @photo, city = @city, capturedate = @date "
                                    + "WHERE pictureid = @pid";

                command.Parameters.AddWithValue("@photo", photographer);
                command.Parameters.AddWithValue("@city", city);
                command.Parameters.Add("@date", SqlDbType.DateTime).Value = capturedate;
                command.Parameters.AddWithValue("@pid", pid);

                connection.Open();

                command.ExecuteNonQuery();

                connection.Close();
            }
        }

        public void GetOriginal(string pid)
        {

            using SqlConnection connection = new SqlConnection(Connections.sqlConnectionString);
            using SqlCommand command = connection.CreateCommand();
            command.CommandText = "SELECT photographer, city, capturedate "
                                + "FROM Pictures "
                                + "WHERE pictureid = @pid";

            command.Parameters.AddWithValue("@pid", pid);

            connection.Open();

            SqlDataReader reader = command.ExecuteReader();
            try
            {
                while (reader.Read())
                {
                    mphotographer = String.Format("{0}", reader[0]);
                    mcity = String.Format("{0}", reader[1]);
                    mcapturedate = (Convert.ToDateTime(reader[2])).ToString("yyyy-MM-dd");
                }
            }
            finally
            {
                reader.Close();
            }

        }

        public void GetGuests(string pictureid)
        {
            List<string> guests = new List<string>();

            using SqlConnection connection = new SqlConnection(Connections.sqlConnectionString);
            using SqlCommand command = connection.CreateCommand();
            command.CommandText = "SELECT guestid "
                                + "FROM SharedPictures "
                                + "WHERE pictureid = @pid";

            command.Parameters.AddWithValue("@pid", pid);

            connection.Open();

            SqlDataReader reader = command.ExecuteReader();
            try
            {
                while (reader.Read())
                {
                    guests.Add(String.Format("{0}", reader[0]));
                }
            }
            finally
            {
                reader.Close();
            }

            mguests = guests;
        }

        public string GetGuestId(string email)
        {
            string guestid = "";

            using SqlConnection connection = new SqlConnection(Connections.sqlConnectionString);
            using SqlCommand command = connection.CreateCommand();
            command.CommandText = "SELECT  Id "
                                + "FROM AspNetUsers "
                                + "WHERE NormalizedEmail  = UPPER(@email)";

            command.Parameters.AddWithValue("@email", email);

            connection.Open();

            SqlDataReader reader = command.ExecuteReader();
            try
            {
                while (reader.Read())
                {
                    guestid = String.Format("{0}", reader[0]);
                }
            }
            finally
            {
                reader.Close();
            }

            return guestid;
        }

        public void DeleteData(string pid)
        {
            using (SqlConnection connection = new SqlConnection(Connections.sqlConnectionString))
            using (SqlCommand command = connection.CreateCommand())
            {
                command.CommandText = "DELETE "
                                    + "FROM UserPictures "
                                    + "WHERE pictureid = @pid";

                command.Parameters.AddWithValue("@pid", pid);

                connection.Open();

                command.ExecuteNonQuery();

                connection.Close();

OnlinePictureStorage/Pages/Home.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using OnlinePictureStorage.Constants;
using OnlinePictureStorage.ViewModels;

namespace OnlinePictureStorage.Pages.Shared
{
    [Authorize]   

    public class HomeModel : PageModel
    {
        public List<string> paths = new List<string>();
        public List<string> pids = new List<string>();

        private readonly UserManager<IdentityUser> userManager;

        public HomeModel(UserManager<IdentityUser> userManager)
        {
            this.userManager = userManager;
        }
        
        public void OnGet()
        {
            string userid = userManager.GetUserId(HttpContext.User);

            List<string> pathlist = new List<string>();
            List<string> pictureids = new List<string>();

            using SqlConnection connection = new SqlConnection(Connections.sqlConnectionString);
            using SqlCommand command = connection.CreateCommand();
            command.CommandText = "SELECT UserPictures.pictureid, Pictures.path "
                                + "FROM UserPictures "
                                + "INNER JOIN Pictures ON UserPictures.pictureid = Pictures.pictureid "
                                + "WHERE UserPictures.userid = @uid";

            command.Parameters.AddWithValue("@uid", userid);

            connection.Open();

            SqlDataReader reader = command.ExecuteReader();
            try 
            {
                while(reader.Read())
                {
                    pathlist.Add(Connections.blobLink +  String.Format("{0}",reader[1]));
                    pictureids.Add(String.Format("{0}", reader[0]));
                }
            }
            finally
            {
                reader.Close();
                paths = pathlist;
                pids = pictureids;
            }

            connection.Close();

        }
    }
}

OnlinePictureStorage/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using OnlinePictureStorage.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlinePictureStorage.Pages
{
    [Authorize]

    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            return RedirectToPage("/Home");
        }

    }
}

OnlinePictureStorage/Pages/Logout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OnlinePictureStorage.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<IdentityUser> signInManager;

        public LogoutModel(SignInManager<IdentityUser> signInManager)
        {
            this.signInManager = signInManager;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await signInManager.SignOutAsync();
            return RedirectToPage("/SignIn");
        }

        public IActionResult OnPostDontLogout()
        {
            return RedirectToPage("/Home");
        }
    }
}

OnlinePictureStorage/Pages/Share.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using OnlinePictureStorage.Constants;
using OnlinePictureStorage.ViewModels;

namespace OnlinePictureStorage.Pages
{
    [Authorize]

    public class ShareModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string pid { set; get; }

        [BindProperty]
        public Share SModel { get; set; }

        private readonly UserManager<IdentityUser> userManager;

        public ShareModel(UserManager<IdentityUser> userManager)
        {
            this.userManager = userManager;
        }

        public void OnGet()
        {
        }

        public  IActionResult OnPostSubmit(string returnURL = null)
        {
            string userid = userManager.GetUserId(HttpContext.User);
            string guestid = GetGuestId(SModel.Email);

            AddShare(userid, guestid, pid);

            return RedirectToPage("/Home");
        }

        public string GetGuestId(string email)
        {
            string guestid = "";

            using SqlConnection connection = new SqlConnection(Connections.sqlConnectionString);
            using SqlCommand command = connection.CreateCommand();
            command.CommandText = "SELECT  Id "
                                + "FROM AspNetUsers "
                                + "WHERE NormalizedEmail  = UPPER(@email)";

            command.Parameters.AddWithValue("@email", email);

            connection.Open();

            SqlDataReader reader = command.ExecuteReader();
            try
            {
                while (reader.Read())
                {
                    guestid = String.Format("{0}", reader[0]);
                }
            }
            finally
            {
                reader.Close();
            }

            return guestid;
        }

        public void AddShare(string ownerid, string guestid, string pictureid)
        {
            using SqlConnection connection = new SqlConnection(Connections.sqlConnectionString);
            using SqlCommand command = connection.CreateCommand();
            command.CommandText = "INSERT INTO SharedPictures (ownerid, guestid, pictureid) "
                                + "VALUES(@oid, @gid, @pid)";

            command.Parameters.AddWithValue("@oid", ownerid);
            command.Parameters.AddWithValue("@gid", guestid);
            command.Parameters.Add("@pid", SqlDbType.UniqueIdentifier).Value = new Guid(pid);

            connection.Open();

            command.ExecuteNonQuery();

            connection.Close();
        }
    }
}

OnlinePictureStorage/Pages/File.cshtml
@page "{pid}"
@model OnlinePictureStorage.Pages.FileModel
@{
}  

<div class="container mt-5">
        <div class="row justify-content-center align-items-center">
            <div class="col-sm-12 col-md-12 col-lg-4">
                @if (Model.oorg == 'o')
                 {
                    <h1 class="mb-3">Owner</h1>
                 }
                 else
                 {
                    <h1 class="mb-3">Guest</h1>
                 }

            <form method="post" enctype="multipart/form-data">

                <div asp-validation-summary="All" class="text-danger"></div>

                <div class="mb-3">
                    <a href="@Model.link" download="@Model.fname" class="d-block mb-4 h-100">
                        <img class="img-fluid img-thumbnail" src="@Model.link" alt="">
                    </a>
                </div>

                @if (Model.oorg == 'o')
                {
                    <div class="mb-3">
                        <button class="btn btn-primary w-100" asp-page="/Share" asp-route-pid="@Model.pid">Share</button>
                    </div>
                }

                @if (Model.oorg == 'g')
                {
                    <div class="mb-3">
                        <button class="btn btn-primary w-100" asp-page-handler="DeclineShare">Decline Share</button>
                    </div>
                }

                <div class="mb-3">
                    <label class="form-label" asp-for="EModel.Date">Date</label>
                    <input type="date" asp-for="EModel.Date" class="form-control" value="@Model.mcapturedate" />
                    <span asp-validation-for="EModel.Date" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="EModel.Photographer">Photographer</label>
                    <input type="text" asp-for="EModel.Photographer" class="form-control" value="@Model.mphotographer" />
                    <span asp-validation-for="EModel.Photographer" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="EModel.City">City</label>
                    <input type="text" asp-for="EModel.City" class="form-control" value="@Model.mcity" />
                    <span asp-validation-for="EModel.City" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <button type="submit" class="btn btn-primary w-100">Update</button>
                </div>

                @if (Model.oorg == 'o')
                {
                    <div class="mb-3">
                        <button class="btn btn-primary w-100" asp-page-handler="Delete">Delete</button>
                    </div>

                    if (!(Model.mguests.Count == 0))
                    {
                        <div class="mb-3">
                            <label class="form-label" asp-for="GModel.Email">Email Address</label>
                            <input type="email" asp-for="GModel.Email" class="form-control" />
                            <span asp-validation-for="GModel.Email" class="text-danger"></span>
                        </div>
                        <button class="btn btn-primary w-100 mb-3" asp-page-handler="Unshare">Unshare</button>
                    }
                }

            </form>
            </div>
        </div>
</div> 

OnlinePictureStorage/Pages/Home.cshtml
@page
@model OnlinePictureStorage.Pages.Shared.HomeModel
@{
}

<div class="container">

    <h1 class="fw-light text-center text-lg-start mt-4 mb-0">Home</h1>

    @{int counter = 0;}

    @if (Model.paths.Count > 0)
    {
        <hr class="mt-2 mb-5">
        <div class="row text-center text-lg-start">

            @foreach (var link in Model.paths)
            {
                <div class="col-lg-3 col-md-4 col-6">
                    <a asp-page="/File" asp-route-pid="@Model.pids.ElementAt(counter)" class="d-block mb-4 h-100">
                        <img class="img-fluid img-thumbnail" src="@link" alt="">
                    </a>
                </div>
                counter++;
            }
        </div>
    }
    else
    {
        <h1>No Images to display!</h1>
    }
</div>

OnlinePictureStorage/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<h1 class="text-black-50"> Index </h1>

OnlinePictureStorage/Pages/Login.cshtml
@page
@model OnlinePictureStorage.Pages.LoginModel
@{
}


<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Login</h1>

            <form method="post">
                <div class="mb-3">
                    <label class="form-label" asp-for="LModel.Email">Email Address</label>
                    <input type="text" asp-for="LModel.Email" class="form-control" />
                    <span asp-validation-for="LModel.Email" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="LModel.Password">Password</label>
                    <input type="password" asp-for="LModel.Password" class="form-control" />
                    <span asp-validation-for="LModel.Password" class="text-danger"></span>
                </div>
                <div class="mb-3 form-check">
                    <input type="checkbox" asp-for="LModel.RememberMe" class="form-check-input" />
                    <label class="form-check-label" asp-for="LModel.RememberMe">Remember Me</label>
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Log In</button>
                </div>
            </form>
        </div>
    </div>
</div>

OnlinePictureStorage/Pages/Logout.cshtml
@page
@model OnlinePictureStorage.Pages.LogoutModel
@{
}

<form method="post">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-12 col-lg-4">
                <p>Are you sure you want to logout?</p>
                <p>
                    <button class="btn btn-primary" asp-page-handler="Logout">Yes</button>
                    <button class="btn btn-light ml-5 border-dark" asp-page-handler="DontLogout">No</button>
                </p>
            </div>
        </div>
    </div>
</form>

OnlinePictureStorage/Pages/Register.cshtml
@page
@model OnlinePictureStorage.Pages.RegisterModel
@{
}

<div class="container mt-5">
    <div class ="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Sign Up</h1>

            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="mb-3">
                    <label class="form-label" asp-for="RegModel.Email">Email Address</label>
                    <input type="text" asp-for="RegModel.Email" class="form-control" />
                    <span asp-validation-for="RegModel.Email" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="RegModel.Password">Password</label>
                    <input type="password" asp-for="RegModel.Password" class="form-control" />
                    <span asp-validation-for="RegModel.Password" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="RegModel.ConfirmPassword">Confirm Password</label>
                    <input type="password" asp-for="RegModel.ConfirmPassword" class="form-control" />
                    <span asp-validation-for="RegModel.ConfirmPassword" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Sign Up</button>
                </div>
            </form>
        </div>
    </div>
</div>

OnlinePictureStorage/Pages/Share.cshtml
@page "{pid}"
@model OnlinePictureStorage.Pages.ShareModel
@{
}

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Share</h1>

            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="mb-3">
                    <label class="form-label" asp-for="SModel.Email">Email Address</label>
                    <input type="email" asp-for="SModel.Email" class="form-control" />
                    <span asp-validation-for="SModel.Email" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary" asp-page-handler="submit">Share</button>
                </div>
            </form>
        </div>
    </div>
</div>

OnlinePictureStorage/Pages/SharedWithMe.cshtml
@page
@model OnlinePictureStorage.Pages.SharedWithMeModel
@{
}
<div class="container">

    <h1 class="fw-light text-center text-lg-start mt-4 mb-0">Shared</h1>

    @{int counter = 0;}

    @if (Model.paths.Count > 0)
    {
        <hr class="mt-2 mb-5">
        <div class="row text-center text-lg-start">

            @foreach (var link in Model.paths)
            {
                <div class="col-lg-3 col-md-4 col-6">
                    <a asp-page="/File" asp-route-pid="@Model.pids.ElementAt(counter)" class="d-block mb-4 h-100">
                        <img class="img-fluid img-thumbnail" src="@link" alt="">
                    </a>
                </div>
                counter++;
            }
        </div>
    }
    else
    {
        <h1>No Images to display!</h1>
    }
</div>

OnlinePictureStorage/Pages/SignIn.cshtml
@page
@model OnlinePictureStorage.Pages.SignInModel
@{
}

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Sign In</h1>

            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="mb-3">
                    <label class="form-label" asp-for="LModel.Email">Email Address</label>
                    <input type="text" asp-for="LModel.Email" class="form-control" />
                    <span asp-validation-for="LModel.Email" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="LModel.Password">Password</label>
                    <input type="password" asp-for="LModel.Password" class="form-control" />
                    <span asp-validation-for="LModel.Password" class="text-danger"></span>
                </div>
                <div class="mb-3 form-check">
                    <input type="checkbox" asp-for="LModel.RememberMe" class="form-check-input" />
                    <label class="form-check-label" asp-for="LModel.RememberMe">Remember Me</label>
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Sign In</button>
                </div>
            </form>
        </div>
    </div>
</div>

OnlinePictureStorage/Pages/Upload.cshtml
@page
@model OnlinePictureStorage.Pages.UploadModel
@{
}

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Upload</h1>

            <form method="post" enctype="multipart/form-data">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="mb-3">
                    <label class="form-label" asp-for="UModel.Date">Date</label>
                    <input type="date" asp-for="UModel.Date" class="form-control" />
                    <span asp-validation-for="UModel.Date" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="UModel.Photographer">Photographer</label>
                    <input type="text" asp-for="UModel.Photographer" class="form-control" />
                    <span asp-validation-for="UModel.Photographer" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="UModel.City">City</label>
                    <input type="text" asp-for="UModel.City" class="form-control" />
                    <span asp-validation-for="UModel.City" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="UModel.File">Photo</label>
                    <input type="file" accept=".bmp, .ico, .jpeg, .jpg, .gif, .tiff, .png" asp-for="UModel.File" class="form-control" />
                    <span asp-validation-for="UModel.File" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Upload</button>
                </div>
            </form>
        </div>
    </div>
</div>